/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfEmployedRouteImport } from './routes/self-employed'
import { Route as MplokakiRouteImport } from './routes/mplokaki'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as IndexRouteImport } from './routes/index'

const SelfEmployedRoute = SelfEmployedRouteImport.update({
  id: '/self-employed',
  path: '/self-employed',
  getParentRoute: () => rootRouteImport,
} as any)
const MplokakiRoute = MplokakiRouteImport.update({
  id: '/mplokaki',
  path: '/mplokaki',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/mplokaki': typeof MplokakiRoute
  '/self-employed': typeof SelfEmployedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/mplokaki': typeof MplokakiRoute
  '/self-employed': typeof SelfEmployedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/mplokaki': typeof MplokakiRoute
  '/self-employed': typeof SelfEmployedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee' | '/mplokaki' | '/self-employed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee' | '/mplokaki' | '/self-employed'
  id: '__root__' | '/' | '/employee' | '/mplokaki' | '/self-employed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRoute
  MplokakiRoute: typeof MplokakiRoute
  SelfEmployedRoute: typeof SelfEmployedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-employed': {
      id: '/self-employed'
      path: '/self-employed'
      fullPath: '/self-employed'
      preLoaderRoute: typeof SelfEmployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mplokaki': {
      id: '/mplokaki'
      path: '/mplokaki'
      fullPath: '/mplokaki'
      preLoaderRoute: typeof MplokakiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRoute,
  MplokakiRoute: MplokakiRoute,
  SelfEmployedRoute: SelfEmployedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
